name: Create release candidate
on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Create release candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure apkovl file location
        run: |
          sed -i \
            -E 's/^(set release_name) \w+$/\1 pre-release/' \
            ./default.pxe ./manual.pxe

      - name: Create Alpine overlay file (apkovl)
        run: |
          chmod 0600 apkovl/etc/iptables/rules*
          tar czf apkovl.tar.gz \
            --owner=0 \
            --group=0 \
            -C apkovl .

      - name: Create development release tag
        run: |
          git config user.name Github Actions
          git config user.email github-actions@github.com
          git tag --force "pre-release"
          git push origin --tags --force

      - name: Delete previous pre-release
        run: |
          gh release delete "pre-release" --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create new pre-release
        run: |
          gh release create "pre-release" \
            --generate-notes \
            --latest=false \
            --prerelease \
            --title "Release Candidate" \
            *.pxe *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
