name: Update pre-release
on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Update pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Alpine overlay file
        run: |
          chmod 0600 apkovl/etc/iptables/rules*
          tar czf apkovl.tar.gz --owner=0 --group=0 -C apkovl .
      - name: Create iSH overlay file
        run: tar czf ishovl.tar.gz --owner=0 --group=0 -C ishovl .
      - uses: ncipollo/release-action@v1
        with:
          name: Release Candidate
          generateReleaseNotes: true
          artifacts: "*.pxe,*.tar.gz"
          artifactErrorsFailBuild: true

          tag: pre-release
          makeLatest: false
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
