name: Update pre-release
on: 
  push:
    branches: 
      - master

jobs:
  pre-release:
    name: Update pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release documentation
        run: |
          FIRST="$(git rev-list --abbrev-commit --max-parents=0 HEAD)"
          LATEST=""
          echo "FIRST: ${FIRST}"
          echo "LATEST: ${LATEST}"
          echo git log --pretty="- [[%h]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/%h)] %s" "${LATEST:-$FIRST}..${GITHUB_SHA}"
          ls -l RELEASE.md
          cat RELEASE.md
      - run: tar cvzf apkovl-pxe.tar.gz --owner=0 --group=0 -C apkovl/pxe .
      - uses: ncipollo/release-action@v1
        with:
          name: Release Candidate
          bodyFile: RELEASE.md
          generateReleaseNotes: false

          tag: pre-release
          makeLatest: false
          prerelease: true
          allowUpdates: true
          
          artifacts: "boot.pxe,apkovl-*.tar.gz"
          artifactErrorsFailBuild: true